name: backend-ci
on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/ci-backend.yml'

concurrency:
  group: backend-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend:
    name: Maven Test & Coverage
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
      - name: Test (H2) + Coverage
        run: mvn -B -Dspring.profiles.active=test verify
      - name: Upload surefire reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: backend/target/surefire-reports
      - name: Upload JaCoCo site
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-coverage
          path: backend/target/site/jacoco
